"""AI trading advisor powered by OpenRouter."""

import httpx
from typing import Optional
from app.config import settings
from app.utils.logger import logger


SYSTEM_PROMPT = """You are an expert GBP/USD day trader with 20 years of experience.
Your job is to give concise, practical trading advice based on current market conditions.
Be direct and actionable. Focus on:
- What the market is doing RIGHT NOW
- Key levels to watch (support/resistance)
- Whether conditions favour a specific bias (bullish/bearish/neutral)
- Any warnings or notable risks
Keep responses under 120 words. Use plain English, no jargon overload."""


async def get_market_commentary(context: dict) -> Optional[str]:
    """
    Get AI commentary from OpenRouter based on current market context.

    context keys:
      price, bid, ask, spread, session, signals, daily_high, daily_low,
      atr_pips, rsi, trend_ema, indicators_summary
    """
    if not settings.OPENROUTER_API_KEY:
        return None

    price = context.get("price", "N/A")
    session = context.get("session", "Unknown")
    signals = context.get("signals", [])
    signal_text = ", ".join([f"{s['direction'].upper()} ({s['strategy']})" for s in signals]) or "None"
    daily_high = context.get("daily_high", "N/A")
    daily_low = context.get("daily_low", "N/A")
    atr_pips = context.get("atr_pips", "N/A")
    rsi = context.get("rsi", "N/A")

    prompt = f"""Current GBP/USD market state:
- Price: {price}
- Session: {session}
- Daily range: {daily_low} – {daily_high}
- ATR (14): {atr_pips} pips
- RSI (14): {rsi}
- Active signals: {signal_text}

Provide a brief market assessment and any actionable advice."""

    headers = {
        "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
        "HTTP-Referer": "https://gppusd-trader.local",
        "X-Title": "GBP/USD Trader",
        "Content-Type": "application/json",
    }

    payload = {
        "model": settings.OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 180,
        "temperature": 0.4,
    }

    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers=headers,
                json=payload,
            )
            if resp.status_code == 200:
                data = resp.json()
                return data["choices"][0]["message"]["content"].strip()
            else:
                logger.warning(f"OpenRouter {resp.status_code}: {resp.text[:200]}")
                return None
    except Exception as e:
        logger.error(f"AI advisor error: {e}")
        return None


async def analyze_trade_setup(signal: dict, context: dict) -> Optional[str]:
    """Get AI commentary specifically for a trade setup."""
    if not settings.OPENROUTER_API_KEY:
        return None

    direction = signal.get("direction", "buy").upper()
    strategy = signal.get("strategy", "unknown")
    entry = signal.get("entry", 0)
    sl = signal.get("stop_loss", 0)
    tp = signal.get("take_profit", 0)
    rr = signal.get("rr_ratio", 0)

    prompt = f"""A {direction} signal has been generated by the {strategy} strategy.
Setup: Entry {entry:.5f} | SL {sl:.5f} | TP {tp:.5f} | R/R 1:{rr:.2f}

Current context: RSI={context.get('rsi','N/A')}, Session={context.get('session','N/A')},
Price position relative to daily range: {context.get('range_position','N/A')}

In 2-3 sentences: Is this setup worth taking? Any caveats?"""

    headers = {
        "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
        "HTTP-Referer": "https://gppusd-trader.local",
        "X-Title": "GBP/USD Trader",
        "Content-Type": "application/json",
    }

    payload = {
        "model": settings.OPENROUTER_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 100,
        "temperature": 0.3,
    }

    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers=headers,
                json=payload,
            )
            if resp.status_code == 200:
                data = resp.json()
                return data["choices"][0]["message"]["content"].strip()
            return None
    except Exception as e:
        logger.error(f"Trade analysis error: {e}")
        return None
